-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "django_migrations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_migrations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"app" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"applied" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "django_content_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_content_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"app_label" varchar(100) NOT NULL,
	"model" varchar(100) NOT NULL,
	CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE("app_label","model")
);
--> statement-breakpoint
CREATE TABLE "auth_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"content_type_id" integer NOT NULL,
	"codename" varchar(100) NOT NULL,
	CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE("content_type_id","codename")
);
--> statement-breakpoint
CREATE TABLE "auth_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(150) NOT NULL,
	CONSTRAINT "auth_group_name_key" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "auth_group_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_id" integer NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE("group_id","permission_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"password" varchar(128) NOT NULL,
	"last_login" timestamp with time zone,
	"is_superuser" boolean NOT NULL,
	"username" varchar(150) NOT NULL,
	"first_name" varchar(150) NOT NULL,
	"last_name" varchar(150) NOT NULL,
	"email" varchar(254) NOT NULL,
	"is_staff" boolean NOT NULL,
	"is_active" boolean NOT NULL,
	"date_joined" timestamp with time zone NOT NULL,
	"role" varchar(10) NOT NULL,
	"phone_number" varchar(15),
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "users_username_key" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "users_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"group_id" integer NOT NULL,
	CONSTRAINT "users_groups_user_id_group_id_fc7788e8_uniq" UNIQUE("user_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "users_user_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_user_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "users_user_permissions_user_id_permission_id_3b86cbdf_uniq" UNIQUE("user_id","permission_id")
);
--> statement-breakpoint
CREATE TABLE "django_admin_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_admin_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"action_time" timestamp with time zone NOT NULL,
	"object_id" text,
	"object_repr" varchar(200) NOT NULL,
	"action_flag" smallint NOT NULL,
	"change_message" text NOT NULL,
	"content_type_id" integer,
	"user_id" bigint NOT NULL,
	CONSTRAINT "django_admin_log_action_flag_check" CHECK (action_flag >= 0)
);
--> statement-breakpoint
CREATE TABLE "processed_data" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "processed_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"data_type" varchar(50) NOT NULL,
	"sub_type" varchar(50) NOT NULL,
	"date" date NOT NULL,
	"processed_json" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "processed_data_data_type_sub_type_date_3961c8e2_uniq" UNIQUE("data_type","sub_type","date")
);
--> statement-breakpoint
CREATE TABLE "LW321" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "loan_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"periode" varchar(30) NOT NULL,
	"kanca" varchar(150) NOT NULL,
	"kode_uker" varchar(50) NOT NULL,
	"uker" varchar(150) NOT NULL,
	"ln_type" varchar(50) NOT NULL,
	"nomor_rekening" varchar(50) NOT NULL,
	"nama_debitur" varchar(200) NOT NULL,
	"plafon" numeric(18, 2),
	"next_pmt_date" date,
	"next_int_pmt_date" date,
	"rate" numeric(7, 4),
	"tgl_menunggak" date,
	"tgl_realisasi" date,
	"tgl_jatuh_tempo" date,
	"jangka_waktu" integer,
	"flag_restruk" varchar(50) NOT NULL,
	"cif_no" varchar(50) NOT NULL,
	"kolektibilitas_lancar" varchar(50) NOT NULL,
	"kolektibilitas_dpk" varchar(50) NOT NULL,
	"kolektibilitas_kurang_lancar" varchar(50) NOT NULL,
	"kolektibilitas_diragukan" varchar(50) NOT NULL,
	"kolektibilitas_macet" varchar(50) NOT NULL,
	"tunggakan_pokok" numeric(18, 2),
	"tunggakan_bunga" numeric(18, 2),
	"tunggakan_pinalti" numeric(18, 2),
	"code" varchar(50) NOT NULL,
	"description" varchar(255) NOT NULL,
	"kol_adk" varchar(50) NOT NULL,
	"pn_pengelola_singlepn" varchar(150) NOT NULL,
	"pn_pengelola_1" varchar(150) NOT NULL,
	"pn_pemrakarsa" varchar(150) NOT NULL,
	"pn_referral" varchar(150) NOT NULL,
	"pn_restruk" varchar(150) NOT NULL,
	"pn_pengelola_2" varchar(150) NOT NULL,
	"pn_pemutus" varchar(150) NOT NULL,
	"pn_crm" varchar(150) NOT NULL,
	"pn_rm_referral_naik_segmentasi" varchar(150) NOT NULL,
	"pn_rm_crr" varchar(150) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "loan_data_nomor_rekening_key" UNIQUE("nomor_rekening")
);
--> statement-breakpoint
CREATE TABLE "upload_history" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upload_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"file_name" varchar(255) NOT NULL,
	"file_path" varchar(100) NOT NULL,
	"file_size" bigint NOT NULL,
	"total_rows" integer NOT NULL,
	"successful_rows" integer NOT NULL,
	"failed_rows" integer NOT NULL,
	"status" varchar(20) NOT NULL,
	"error_log" text,
	"notes" text,
	"created_at" timestamp with time zone NOT NULL,
	"completed_at" timestamp with time zone,
	"uploaded_by_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "django_session" (
	"session_key" varchar(40) PRIMARY KEY NOT NULL,
	"session_data" text NOT NULL,
	"expire_date" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_user_id_f500bee5_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_group_id_2f3517aa_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissions_user_id_92473840_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissio_permission_id_6d08dcd2_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upload_history" ADD CONSTRAINT "upload_history_uploaded_by_id_d40cb3a9_fk_users_id" FOREIGN KEY ("uploaded_by_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" USING btree ("name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" USING btree ("group_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" USING btree ("permission_id" int4_ops);--> statement-breakpoint
CREATE INDEX "users_username_e8658fc8_like" ON "users" USING btree ("username" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "users_groups_group_id_2f3517aa" ON "users_groups" USING btree ("group_id" int4_ops);--> statement-breakpoint
CREATE INDEX "users_groups_user_id_f500bee5" ON "users_groups" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "users_user_permissions_permission_id_6d08dcd2" ON "users_user_permissions" USING btree ("permission_id" int4_ops);--> statement-breakpoint
CREATE INDEX "users_user_permissions_user_id_92473840" ON "users_user_permissions" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "processed_data_data_type_927b7fb2" ON "processed_data" USING btree ("data_type" text_ops);--> statement-breakpoint
CREATE INDEX "processed_data_data_type_927b7fb2_like" ON "processed_data" USING btree ("data_type" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "processed_data_date_7817b3a1" ON "processed_data" USING btree ("date" date_ops);--> statement-breakpoint
CREATE INDEX "loan_data_nomor_r_aaa7d0_idx" ON "LW321" USING btree ("nomor_rekening" text_ops);--> statement-breakpoint
CREATE INDEX "loan_data_nomor_rekening_40f18396_like" ON "LW321" USING btree ("nomor_rekening" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "loan_data_periode_6df3a4_idx" ON "LW321" USING btree ("periode" text_ops,"kolektibilitas_macet" text_ops);--> statement-breakpoint
CREATE INDEX "loan_data_periode_7e1f2d71" ON "LW321" USING btree ("periode" text_ops);--> statement-breakpoint
CREATE INDEX "loan_data_periode_7e1f2d71_like" ON "LW321" USING btree ("periode" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "loan_data_periode_db8448_idx" ON "LW321" USING btree ("periode" text_ops,"kanca" text_ops);--> statement-breakpoint
CREATE INDEX "upload_history_uploaded_by_id_d40cb3a9" ON "upload_history" USING btree ("uploaded_by_id" int8_ops);--> statement-breakpoint
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" USING btree ("expire_date" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" USING btree ("session_key" varchar_pattern_ops);
*/