# Generated by Django 4.2.7 on 2026-04-28 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(db_index=True, max_length=50)),
                ('sub_type', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('processed_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Processed Data',
                'verbose_name_plural': 'Processed Data',
                'db_table': 'processed_data',
                'ordering': ['-date'],
                'unique_together': {('data_type', 'sub_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LW321',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(db_index=True, max_length=20)),
                ('kanca', models.CharField(blank=True, max_length=100)),
                ('kode_uker', models.CharField(blank=True, max_length=10)),
                ('uker', models.CharField(blank=True, max_length=100)),
                ('ln_type', models.CharField(blank=True, max_length=10)),
                ('nomor_rekening', models.CharField(db_index=True, max_length=100)),
                ('nama_debitur', models.CharField(blank=True, max_length=100)),
                ('plafon', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('next_pmt_date', models.CharField(blank=True, max_length=20, null=True)),
                ('next_int_pmt_date', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tgl_menunggak', models.CharField(blank=True, max_length=20, null=True)),
                ('tgl_realisasi', models.CharField(blank=True, max_length=20, null=True)),
                ('tgl_jatuh_tempo', models.CharField(blank=True, max_length=20, null=True)),
                ('jangka_waktu', models.CharField(blank=True, max_length=10, null=True)),
                ('flag_restruk', models.CharField(blank=True, max_length=10)),
                ('cif_no', models.CharField(blank=True, max_length=100)),
                ('kolektibilitas_lancar', models.CharField(blank=True, max_length=100)),
                ('kolektibilitas_dpk', models.CharField(blank=True, max_length=100)),
                ('kolektibilitas_kurang_lancar', models.CharField(blank=True, max_length=100)),
                ('kolektibilitas_diragukan', models.CharField(blank=True, max_length=100)),
                ('kolektibilitas_macet', models.CharField(blank=True, max_length=100)),
                ('tunggakan_pokok', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tunggakan_bunga', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tunggakan_pinalti', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('kol_adk', models.CharField(blank=True, max_length=10)),
                ('pn_rm', models.CharField(blank=True, max_length=20)),
                ('nama_rm', models.CharField(blank=True, max_length=100)),
                ('os', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('nasabah', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('dub_nasabah', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LW321 data',
                'verbose_name_plural': 'LW321 data',
                'db_table': 'lw321',
                'ordering': ['-periode', 'kanca', 'nomor_rekening'],
                'indexes': [models.Index(fields=['periode', 'kanca'], name='lw321_periode_8b73c1_idx'), models.Index(fields=['periode', 'kolektibilitas_macet'], name='lw321_periode_b21326_idx'), models.Index(fields=['nomor_rekening'], name='lw321_nomor_r_907b32_idx'), models.Index(fields=['periode', 'nomor_rekening'], name='lw321_periode_b79806_idx')],
            },
        ),
        migrations.CreateModel(
            name='KomitmenUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField(db_index=True, help_text='Periode bulan komitmen (contoh: 2025-11-01)', unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(help_text='Nama file yang diupload', max_length=255)),
                ('row_count', models.IntegerField(default=0, help_text='Jumlah baris data (tidak termasuk total row)')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Catatan validasi atau error messages')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komitmen Upload',
                'verbose_name_plural': 'Komitmen Uploads',
                'db_table': 'komitmen_upload',
                'ordering': ['-periode'],
            },
        ),
        migrations.CreateModel(
            name='KomitmenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField(db_index=True, help_text='Periode bulan komitmen')),
                ('kode_kanca', models.IntegerField(db_index=True, help_text='Kode KANCA sebagai integer')),
                ('kode_uker', models.CharField(db_index=True, max_length=20)),
                ('nama_kanca', models.CharField(max_length=100)),
                ('nama_uker', models.CharField(max_length=100)),
                ('kur_deb', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kur_os', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kur_pl', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kur_npl', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kur_dpk', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('small_deb', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('small_os', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('small_pl', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('small_npl', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('small_dpk', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kecil_ncc_deb', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kecil_ncc_os', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kecil_ncc_pl', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kecil_ncc_npl', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kecil_ncc_dpk', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kecil_cc_deb', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kecil_cc_os', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kecil_cc_pl', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kecil_cc_npl', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('kecil_cc_dpk', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='dashboard.komitmenupload')),
            ],
            options={
                'verbose_name': 'Komitmen Data',
                'verbose_name_plural': 'Komitmen Data',
                'db_table': 'komitmen_data',
                'ordering': ['kode_kanca', 'kode_uker'],
                'indexes': [models.Index(fields=['periode', 'kode_uker'], name='komitmen_da_periode_6c6a51_idx'), models.Index(fields=['periode', 'kode_kanca'], name='komitmen_da_periode_8d27fb_idx')],
                'unique_together': {('periode', 'kode_uker')},
            },
        ),
    ]
