# Generated by Django 4.2.7 on 2025-10-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(db_index=True, max_length=50)),
                ('sub_type', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('processed_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Processed Data',
                'verbose_name_plural': 'Processed Data',
                'db_table': 'processed_data',
                'ordering': ['-date'],
                'unique_together': {('data_type', 'sub_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LoanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(db_index=True, max_length=30)),
                ('kanca', models.CharField(blank=True, max_length=150)),
                ('kode_uker', models.CharField(blank=True, max_length=50)),
                ('uker', models.CharField(blank=True, max_length=150)),
                ('ln_type', models.CharField(blank=True, max_length=50)),
                ('nomor_rekening', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nama_debitur', models.CharField(blank=True, max_length=200)),
                ('plafon', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('next_pmt_date', models.DateField(blank=True, null=True)),
                ('next_int_pmt_date', models.DateField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tgl_menunggak', models.DateField(blank=True, null=True)),
                ('tgl_realisasi', models.DateField(blank=True, null=True)),
                ('tgl_jatuh_tempo', models.DateField(blank=True, null=True)),
                ('jangka_waktu', models.IntegerField(blank=True, null=True)),
                ('flag_restruk', models.CharField(blank=True, max_length=50)),
                ('cif_no', models.CharField(blank=True, max_length=50)),
                ('kolektibilitas_lancar', models.CharField(blank=True, max_length=50)),
                ('kolektibilitas_dpk', models.CharField(blank=True, max_length=50)),
                ('kolektibilitas_kurang_lancar', models.CharField(blank=True, max_length=50)),
                ('kolektibilitas_diragukan', models.CharField(blank=True, max_length=50)),
                ('kolektibilitas_macet', models.CharField(blank=True, max_length=50)),
                ('tunggakan_pokok', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tunggakan_bunga', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tunggakan_pinalti', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('kol_adk', models.CharField(blank=True, max_length=50)),
                ('pn_pengelola_singlepn', models.CharField(blank=True, max_length=150)),
                ('pn_pengelola_1', models.CharField(blank=True, max_length=150)),
                ('pn_pemrakarsa', models.CharField(blank=True, max_length=150)),
                ('pn_referral', models.CharField(blank=True, max_length=150)),
                ('pn_restruk', models.CharField(blank=True, max_length=150)),
                ('pn_pengelola_2', models.CharField(blank=True, max_length=150)),
                ('pn_pemutus', models.CharField(blank=True, max_length=150)),
                ('pn_crm', models.CharField(blank=True, max_length=150)),
                ('pn_rm_referral_naik_segmentasi', models.CharField(blank=True, max_length=150)),
                ('pn_rm_crr', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LW321',
                'verbose_name_plural': 'LW321',
                'db_table': 'LW321',
                'ordering': ['-periode', 'kanca', 'nomor_rekening'],
                'indexes': [models.Index(fields=['periode', 'kanca'], name='LW321_periode_db8448_idx'), models.Index(fields=['periode', 'kolektibilitas_macet'], name='LW321_periode_6df3a4_idx'), models.Index(fields=['nomor_rekening'], name='LW321_nomor_r_aaa7d0_idx')],
            },
        ),
    ]
