# Generated by Django 4.2.7 on 2025-11-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lw321',
            options={'ordering': ['-periode', 'kanca', 'nomor_rekening'], 'verbose_name': 'LW321 data', 'verbose_name_plural': 'LW321 data'},
        ),
        migrations.RenameIndex(
            model_name='lw321',
            new_name='LW321_periode_88d949_idx',
            old_name='LW321_periode_db8448_idx',
        ),
        migrations.RenameIndex(
            model_name='lw321',
            new_name='LW321_periode_dc5f0b_idx',
            old_name='LW321_periode_6df3a4_idx',
        ),
        migrations.RenameIndex(
            model_name='lw321',
            new_name='LW321_nomor_r_1558c0_idx',
            old_name='LW321_nomor_r_aaa7d0_idx',
        ),
    ]
