# Generated by Django 4.2.7 on 2025-11-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_table_lowercase'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lw321',
            new_name='lw321_periode_8b73c1_idx',
            old_name='LW321_periode_88d949_idx',
        ),
        migrations.RenameIndex(
            model_name='lw321',
            new_name='lw321_periode_b21326_idx',
            old_name='LW321_periode_dc5f0b_idx',
        ),
        migrations.RenameIndex(
            model_name='lw321',
            new_name='lw321_nomor_r_907b32_idx',
            old_name='LW321_nomor_r_1558c0_idx',
        ),
        migrations.AlterModelTable(
            name='lw321',
            table='lw321',
        ),
    ]
