# Generated by Django 5.2.6 on 2025-12-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_lw321_periode_88d949_idx_lw321_periode_8b73c1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lw321',
            name='nomor_rekening',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='lw321',
            index=models.Index(fields=['periode', 'nomor_rekening'], name='lw321_periode_b79806_idx'),
        ),
    ]
