# Generated by Django 5.2.6 on 2025-12-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_lw321_nomor_rekening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lw321',
            name='pn_crm',
        ),
        migrations.RemoveField(
            model_name='lw321',
            name='pn_pemrakarsa',
        ),
        migrations.RemoveField(
            model_name='lw321',
            name='pn_pemutus',
        ),
        migrations.RemoveField(
            model_name='lw321',
            name='pn_pengelola_1',
        ),
        migrations.RemoveField(
            model_name='lw321',
            name='pn_pengelola_2',
        ),
        migrations.RemoveField(
            model_name='lw321',
            name='pn_referral',
        ),
        migrations.RemoveField(
            model_name='lw321',
            name='pn_restruk',
        ),
        migrations.RemoveField(
            model_name='lw321',
            name='pn_rm_crr',
        ),
        migrations.RemoveField(
            model_name='lw321',
            name='pn_rm_referral_naik_segmentasi',
        ),
        migrations.AddField(
            model_name='lw321',
            name='nama_rm',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
