# Generated by Django 5.2.6 on 2025-12-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_lw321_pn_crm_remove_lw321_pn_pemrakarsa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lw321',
            old_name='pn_pengelola_singlepn',
            new_name='pn_rm',
        ),
        migrations.AddField(
            model_name='lw321',
            name='os',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
