# Generated by Django 5.2.6 on 2025-12-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_fix_os_empty_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='lw321',
            name='dub_nasabah',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lw321',
            name='nasabah',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
