# Generated by Django 5.2.6 on 2025-12-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_lw321_dub_nasabah_lw321_nasabah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lw321',
            name='flag_restruk',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='jangka_waktu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='kanca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='kode_uker',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='kol_adk',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='ln_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='nama_debitur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='nama_rm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='next_int_pmt_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='next_pmt_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='periode',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='pn_rm',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='tgl_jatuh_tempo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='tgl_menunggak',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='tgl_realisasi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='uker',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
