# Generated by Django 5.2.6 on 2025-12-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_field_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lw321',
            name='dub_nasabah',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
    ]
