# Generated by Django 5.2.6 on 2025-12-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_change_dub_nasabah_to_varchar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lw321',
            name='dub_nasabah',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
