# Generated by Django 5.2.6 on 2025-12-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_fix_dub_nasabah_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lw321',
            name='cif_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='kanca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='kolektibilitas_diragukan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='kolektibilitas_dpk',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='kolektibilitas_kurang_lancar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='kolektibilitas_lancar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='kolektibilitas_macet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='nama_debitur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='nama_rm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='nomor_rekening',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lw321',
            name='uker',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
