# Generated by Django 5.2.6 on 2025-12-25 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_increase_varchar_to_100'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KomitmenUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField(db_index=True, help_text='Periode bulan komitmen (contoh: 2025-11-01)', unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(help_text='Nama file yang diupload', max_length=255)),
                ('row_count', models.IntegerField(default=0, help_text='Jumlah baris data (tidak termasuk total row)')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Catatan validasi atau error messages')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komitmen Upload',
                'verbose_name_plural': 'Komitmen Uploads',
                'db_table': 'komitmen_upload',
                'ordering': ['-periode'],
            },
        ),
        migrations.CreateModel(
            name='KomitmenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField(db_index=True, help_text='Periode bulan komitmen')),
                ('kode_kanca', models.CharField(db_index=True, max_length=10)),
                ('kode_uker', models.CharField(db_index=True, max_length=20)),
                ('nama_kanca', models.CharField(max_length=100)),
                ('nama_uker', models.CharField(max_length=100)),
                ('kur_deb', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kur_os', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kur_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kur_npl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kur_dpk', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('small_deb', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('small_os', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('small_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('small_npl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('small_dpk', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kecil_ncc_deb', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kecil_ncc_os', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kecil_ncc_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kecil_ncc_npl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kecil_ncc_dpk', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kecil_cc_deb', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kecil_cc_os', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kecil_cc_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kecil_cc_npl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kecil_cc_dpk', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='dashboard.komitmenupload')),
            ],
            options={
                'verbose_name': 'Komitmen Data',
                'verbose_name_plural': 'Komitmen Data',
                'db_table': 'komitmen_data',
                'ordering': ['kode_kanca', 'kode_uker'],
                'indexes': [models.Index(fields=['periode', 'kode_uker'], name='komitmen_da_periode_6c6a51_idx'), models.Index(fields=['periode', 'kode_kanca'], name='komitmen_da_periode_8d27fb_idx')],
                'unique_together': {('periode', 'kode_uker')},
            },
        ),
    ]
